#!/bin/bash

#sudo apt update
#sudo apt upgrade
sudo apt install hostapd dnsmasq iptables
sudo systemctl stop hostapd
sudo systemctl unmask hostapd
sudo systemctl disable hostapd
sudo systemctl stop dnsmasq
sudo systemctl disable dnsmasq

HERE=$(dirname "${BASH_SOURCE[0]}")

mkdir -p "$HERE"/supplicant/etc
###### 1: /etc/dhcpcd.conf
test -f "$HERE"/supplicant/etc/dhcpcd.conf  || cp /etc/dhcpcd.conf  "$HERE"/supplicant/etc/dhcpcd.conf

###### 2: /etc/dnsmasq.conf  # (probably doesn't matter)
test -f "$HERE"/supplicant/etc/dnsmasq.conf || cp /etc/dnsmasq.conf "$HERE"/supplicant/etc/dnsmasq.conf

###### 3: /etc/hostapd/hostapd.conf  # (doesn't matter)

###### 4: /etc/network/interfaces.d/wireless-access-point
mkdir -p "$HERE"/supplicant/etc/network/interfaces.d
echo > "$HERE"/supplicant/etc/network/interfaces.d/wireless-access-point  # empty file, to disable

###### 5: activation script
cat<<EOF>"$HERE"/supplicant/activate
#!/bin/bash
sudo cp -Rv \$(dirname "\${BASH_SOURCE[0]}")/etc/* /etc/
sudo systemctl stop dnsmasq
sudo systemctl disable dnsmasq

sudo systemctl stop hostapd
sudo systemctl unmask hostapd
sudo systemctl disable hostapd

sudo systemctl restart dhcpcd
sudo systemctl restart wpa_supplicant
EOF
chmod a+x "$HERE"/supplicant/activate



mkdir -p "$HERE"/access-point/etc
###### 1: /etc/dhcpcd.conf
cp "$HERE"/supplicant/etc/dhcpcd.conf "$HERE"/access-point/etc/dhcpcd.conf
cat <<EOF>>"$HERE"/access-point/etc/dhcpcd.conf
interface wlan0
	static ip_address=192.168.4.1/24
	nohook wpa_supplicant
EOF

###### 2: /etc/dnsmasq.conf
cat <<EOF>"$HERE"/access-point/etc/dnsmasq.conf
interface=wlan0      # Use interface wlan0  
server=1.1.1.1       # Use Cloudflare DNS  
dhcp-range=192.168.4.2,192.168.4.20,12h # IP range and lease time  
EOF

###### 3: /etc/hostapd/hostapd.conf
mkdir -p "$HERE"/access-point/etc/hostapd
cat<<EOF>"$HERE"/access-point/etc/hostapd/hostapd.conf
interface=wlan0
driver=nl80211
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=0
macaddr_acl=0
ignore_broadcast_ssid=0
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
# This is the name of the network:
ssid=WirelessDSIMobileUnit
# The network passphrase:
wpa_passphrase=blah1234
EOF

###### 4: /etc/network/interfaces.d/wireless-access-point
mkdir -p "$HERE"/access-point/etc/network/interfaces.d
cat <<EOF>"$HERE"/access-point/etc/network/interfaces.d/wireless-access-point
iface wlan0 inet static
    hostapd /etc/hostapd/hostapd.conf
EOF

###### 5: activation script
cat<<EOF>"$HERE"/access-point/activate
#!/bin/bash
sudo cp -Rv \$(dirname "\${BASH_SOURCE[0]}")/etc/* /etc/
sudo systemctl restart dhcpcd

sudo systemctl unmask hostapd
sudo systemctl enable hostapd
sudo systemctl start hostapd

sudo systemctl enable dnsmasq
sudo systemctl start dnsmasq
EOF
chmod a+x "$HERE"/access-point/activate

